namespace: netways
name: backup
version: 0.1.0-beta
readme: README.md
authors:
  - Thomas Widhalm <thomas.widhalm@netways.de>
  - Marc Rupprecht <marc.rupprecht@netways.de>
description: >
  This collection provides a collection of backup tools
license:
  - GPL-3.0-or-later
tags:
  - backup
  - rsnapshot
dependencies: {}
repository: https://github.com/NETWAYS/ansible-collection-backup
documentation: https://github.com/NETWAYS/ansible-collection-backup/tree/main/docs
homepage: http://netways.de
issues: https://github.com/NETWAYS/ansible-collection-backup/issues
build_ignore:
  - yamllint.yaml
  - .cache
  - molecule
  - tests
  - .gitignore
  - .github
  - .gitlab-ci.yml
  - __pycache__
  - 'venv*'
  - .idea
  - '*.tar.gz'
