---

- name: Print MySQL / MariaDB version
  copy:
    content: "{{ minimalbackup_mysql_info.version.full }}"
    dest: "{{ minimalbackup_tmpdir }}/{{ ansible_hostname }}_mysql_version"
  delegate_to: localhost

- name: Fetch MySQL / MariaDB variables
  community.mysql.mysql_query:
    query: "SHOW VARIABLES"
  changed_when: false
  register: minimalbackup_mysql_variables

- name: Print MySQL / MariaDB variables
  copy:
    content: "{{ minimalbackup_mysql_variables }}"
    dest: "{{ minimalbackup_tmpdir }}/{{ ansible_hostname }}_mysql_variables"
  delegate_to: localhost
  tags:
    - molecule-idempotence-notest
