---

- name: Converge
  hosts: all
  collections:
    - widhalmt.backup
  tasks:

    - name: "Include Rsnapshot"
      include_role:
        name: rsnapshot

    - name: "Include Bachup"
      include_role:
        name: backup
