---

- name: Converge
  hosts: all
  vars:
    minimalbackup_fetch_directories: true
  collections:
    - netways.backup
  tasks:

    - name: "Include Rsnapshot"
      include_role:
        name: rsnapshot

    - name: "Include Backup"
      include_role:
        name: backup

    - name: "Set up database for data collection"
      include_role:
        name: geerlingguy.mysql

    - name: "Include Minimalbackup"
      include_role:
        name: minimalbackup
