---

- name: Converge
  hosts: all
  collections:
    - netways.backup
  tasks:

    - name: "Include Rsnapshot"
      include_role:
        name: rsnapshot

    - name: "Include Backup"
      include_role:
        name: backup

    - name: "Include Minimalbackup"
      include_role:
        name: minimalbackup
