---
- name: Prepare
  hosts: all
  vars:
    mysql_root_username: root
    mysql_root_password: netways0815!
    mysql_databases:
      - name: testDatabase
        encoding: utf8
        collation: utf8_general_ci
        replicate: 0
    mysql_users: 
      - name: testDatabase
        host: 127.0.0.1
        password: netways0815!
        priv: testUser.*:ALL
        
  pre_tasks:
    - name: Refresh apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install git
      package:
        name: git

    - name: Install packages for Debian
      package:
        name:
          - gpg
          - gpg-agent
          - procps
          - curl
      when: ansible_os_family == "Debian"

    - name: Install packages for RedHat
      package:
        name:
          - cronie
      when: ansible_os_family == "RedHat"
    
    - name: restart AppArmor
      command: service apparmor stop
      when: ansible_distribution == 'Debian'
    
  roles:
    - geerlingguy.mysql
