---

- hosts: all
  tasks:
    - name: Run default rsnapshot
      command: >
        /bin/date >
        /root/rsnapshot//timestamp.hourly;
        /usr/bin/rsnapshot
        -c /etc/rsnapshot.conf
        hourly

    - name: Check for backup
      stat:
        path: /opt/backup/rsnapshot/hourly.0/localhost/root/rsnapshot/timestamp.hourly
